// <auto-generated />
namespace DOAN_LTW_HVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addIDonhang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIDonhang));
        
        string IMigrationMetadata.Id
        {
            get { return "202312040941293_addIDonhang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
